### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda

### ISSUE THREAD

**Issue by yinggo** [ruinmessi/RFBNet#41]
Environment:
Linux 16.04 
python 3.7
cuda 8.0

When I  compile the nms and coco tools:
by using
./make.sh
I got this kind of error:
`running build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
building 'nms.cpu_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c nms/cpu_nms.c -o build/temp.linux-x86_64-3.7/nms/cpu_nms.o -Wno-cpp -Wno-unused-function
nms/cpu_nms.c: In function ‘__pyx_pf_3nms_7cpu_nms_2cpu_soft_nms’:
nms/cpu_nms.c:3172:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_8 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                 ^
nms/cpu_nms.c:3683:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_8 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                 ^
nms/cpu_nms.c: In function ‘__Pyx_PyCFunction_FastCall’:
nms/cpu_nms.c:8431:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
            ^
nms/cpu_nms.c: In function ‘__Pyx__ExceptionSave’:
nms/cpu_nms.c:8892:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                   ^
nms/cpu_nms.c:8893:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                    ^
nms/cpu_nms.c:8894:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                 ^
nms/cpu_nms.c: In function ‘__Pyx__ExceptionReset’:
nms/cpu_nms.c:8901:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                      ^
nms/cpu_nms.c:8902:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                       ^
nms/cpu_nms.c:8903:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                    ^
nms/cpu_nms.c:8904:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = type;
           ^
nms/cpu_nms.c:8905:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = value;
           ^
nms/cpu_nms.c:8906:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = tb;
           ^
nms/cpu_nms.c: In function ‘__Pyx__GetException’:
nms/cpu_nms.c:8961:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                      ^
nms/cpu_nms.c:8962:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                       ^
nms/cpu_nms.c:8963:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                    ^
nms/cpu_nms.c:8964:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
           ^
nms/cpu_nms.c:8965:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
           ^
nms/cpu_nms.c:8966:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
           ^
error: command 'gcc' failed with exit status 1
`
Anyone can help? How to solve this problem?

**Comment by ruinmessi** [comment]
@yinggo  What's the version of your pytorch. We only support 0.4.0 now, and 0.4.1 maybe incompatible.

**Comment by yinggo** [comment]
> @yinggo What's the version of your pytorch. We only support 0.4.0 now, and 0.4.1 maybe incompatible.

Thanks! I changed to 0.4.0, now it works.

**Comment by yinggo** [comment]
I meet a new error, can you give some suggestions? @ruinmessi 
`Initializing weights...
Loading Dataset...
Training RFB_E_vgg on VOC0712
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train_RFB.py", line 257, in <module>
    train()
  File "train_RFB.py", line 220, in train
    out = net(images)
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ds1/Downloads/RFBNet/models/RFB_Net_E_vgg.py", line 238, in forward
    x = self.base[k](x)
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu:58
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f188a4780f0>>
Traceback (most recent call last):
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/ds1/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/ds1/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/ds1/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/ds1/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/ds1/anaconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/ds1/anaconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused`

Python 3.6
pytorch: 0.4.0
cuda 8.0
GPU: TITAN X.

**Comment by ruinmessi** [comment]
@yinggo Does this error end the training process? It seems a bug of multiporcess in dataloader, and it would not break down the whole program. And you may set cv2.setNumThreads(0) after import cv2.
